apiVersion: v1
kind: Service
metadata:
  name: ecommerce-monitor-service
  labels:
    app: ecommerce-monitor
spec:
  selector:
    app: ecommerce-monitor
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009